{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "선생님이랑 함께 한 네이버뉴스 수집 파일 보면서 따라하자!\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import requests\n",
    "from bs4 import BeautifulSoup\n",
    "url = \"http://ncov.mohw.go.kr/bdBoardList_Real.do?brdId=1&brdGubun=14&ncvContSeq=&contSeq=&board_id=&gubun=\"\n",
    "html = requests.get(url).text\n",
    "soup = BeautifulSoup(html, \"html.parser\")\n",
    "all = soup.find(\"div\" , {\"class\" : \"data_table mgt8\"})\n",
    "th = all.find_all(\"th\", {\"scope\" : \"row\"})\n",
    "tr = all.find_all(\"tr\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "bs4.element.ResultSet"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "type(tr)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[<th scope=\"row\">미국</th>,\n",
       " <th scope=\"row\">브라질</th>,\n",
       " <th scope=\"row\">인도</th>,\n",
       " <th scope=\"row\">러시아</th>,\n",
       " <th scope=\"row\">남아프리카공화국</th>,\n",
       " <th scope=\"row\">멕시코</th>,\n",
       " <th scope=\"row\">페루</th>,\n",
       " <th scope=\"row\">콜롬비아</th>,\n",
       " <th scope=\"row\">칠레</th>,\n",
       " <th scope=\"row\">스페인</th>,\n",
       " <th scope=\"row\">이란</th>,\n",
       " <th scope=\"row\">영국</th>,\n",
       " <th scope=\"row\">사우디아라비아</th>,\n",
       " <th scope=\"row\">파키스탄</th>,\n",
       " <th scope=\"row\">아르헨티나</th>,\n",
       " <th scope=\"row\">방글라데시</th>,\n",
       " <th scope=\"row\">이탈리아</th>,\n",
       " <th scope=\"row\">필리핀</th>,\n",
       " <th scope=\"row\">인도네시아</th>,\n",
       " <th scope=\"row\">카자흐스탄</th>,\n",
       " <th scope=\"row\">중국</th>,\n",
       " <th scope=\"row\">싱가포르</th>,\n",
       " <th scope=\"row\">일본</th>,\n",
       " <th scope=\"row\">키르키스스탄</th>,\n",
       " <th scope=\"row\">우즈베키스탄</th>,\n",
       " <th scope=\"row\">호주</th>,\n",
       " <th scope=\"row\">말레이시아</th>,\n",
       " <th scope=\"row\">태국</th>,\n",
       " <th scope=\"row\">베트남</th>,\n",
       " <th scope=\"row\">한국</th>]"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "th"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "미국\n",
      "----------\n",
      "브라질\n",
      "----------\n",
      "인도\n",
      "----------\n",
      "러시아\n",
      "----------\n",
      "남아프리카공화국\n",
      "----------\n",
      "멕시코\n",
      "----------\n",
      "페루\n",
      "----------\n",
      "콜롬비아\n",
      "----------\n",
      "칠레\n",
      "----------\n",
      "스페인\n",
      "----------\n",
      "이란\n",
      "----------\n",
      "영국\n",
      "----------\n",
      "사우디아라비아\n",
      "----------\n",
      "파키스탄\n",
      "----------\n",
      "아르헨티나\n",
      "----------\n",
      "방글라데시\n",
      "----------\n",
      "이탈리아\n",
      "----------\n",
      "필리핀\n",
      "----------\n",
      "인도네시아\n",
      "----------\n",
      "카자흐스탄\n",
      "----------\n",
      "중국\n",
      "----------\n",
      "싱가포르\n",
      "----------\n",
      "일본\n",
      "----------\n",
      "키르키스스탄\n",
      "----------\n",
      "우즈베키스탄\n",
      "----------\n",
      "호주\n",
      "----------\n",
      "말레이시아\n",
      "----------\n",
      "태국\n",
      "----------\n",
      "베트남\n",
      "----------\n",
      "한국\n",
      "----------\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "['미국',\n",
       " '브라질',\n",
       " '인도',\n",
       " '러시아',\n",
       " '남아프리카공화국',\n",
       " '멕시코',\n",
       " '페루',\n",
       " '콜롬비아',\n",
       " '칠레',\n",
       " '스페인',\n",
       " '이란',\n",
       " '영국',\n",
       " '사우디아라비아',\n",
       " '파키스탄',\n",
       " '아르헨티나',\n",
       " '방글라데시',\n",
       " '이탈리아',\n",
       " '필리핀',\n",
       " '인도네시아',\n",
       " '카자흐스탄',\n",
       " '중국',\n",
       " '싱가포르',\n",
       " '일본',\n",
       " '키르키스스탄',\n",
       " '우즈베키스탄',\n",
       " '호주',\n",
       " '말레이시아',\n",
       " '태국',\n",
       " '베트남',\n",
       " '한국']"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "country_name = []\n",
    "for item in th :\n",
    "    try :\n",
    "        #country = item 에서 나라이름만 뽑아옴.\n",
    "        country = item.text    # 알기\n",
    "        print(country)   #print(country)\n",
    "        print('-' *10)\n",
    "        country_name.append(country)\n",
    "    except :\n",
    "        print(\"No country\")\n",
    "\n",
    "\n",
    "country_name"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[<tr>\n",
       " <th rowspan=\"2\" scope=\"col\">국가</th>\n",
       " <th colspan=\"2\" scope=\"col\">감염자</th>\n",
       " <th colspan=\"2\" scope=\"col\">사망자</th>\n",
       " <th rowspan=\"2\" scope=\"col\">사망률</th>\n",
       " </tr>,\n",
       " <tr>\n",
       " <th scope=\"col\">인원</th>\n",
       " <th scope=\"col\">발생률<span class=\"txt_ntc_bold\"> (*)</span></th>\n",
       " <th scope=\"col\">인원</th>\n",
       " <th scope=\"col\">발생률<span class=\"txt_ntc_bold\"> (*)</span></th>\n",
       " </tr>,\n",
       " <tr>\n",
       " <th scope=\"row\">미국</th>\n",
       " <td>5,356,244</td>\n",
       " <td>1627.54</td>\n",
       " <td>169,423</td>\n",
       " <td>51.5</td>\n",
       " <td>3.16</td>\n",
       " </tr>,\n",
       " <tr>\n",
       " <th scope=\"row\">브라질</th>\n",
       " <td>3,317,096</td>\n",
       " <td>1561.72</td>\n",
       " <td>107,232</td>\n",
       " <td>50.5</td>\n",
       " <td>3.23</td>\n",
       " </tr>,\n",
       " <tr>\n",
       " <th scope=\"row\">인도</th>\n",
       " <td>2,526,192</td>\n",
       " <td>184.57</td>\n",
       " <td>49,036</td>\n",
       " <td>3.6</td>\n",
       " <td>1.94</td>\n",
       " </tr>,\n",
       " <tr>\n",
       " <th scope=\"row\">러시아</th>\n",
       " <td>917,884</td>\n",
       " <td>637.86</td>\n",
       " <td>15,617</td>\n",
       " <td>10.9</td>\n",
       " <td>1.7</td>\n",
       " </tr>,\n",
       " <tr>\n",
       " <th scope=\"row\">남아프리카공화국</th>\n",
       " <td>579,140</td>\n",
       " <td>996.8</td>\n",
       " <td>11,556</td>\n",
       " <td>19.9</td>\n",
       " <td>2</td>\n",
       " </tr>,\n",
       " <tr>\n",
       " <th scope=\"row\">멕시코</th>\n",
       " <td>517,714</td>\n",
       " <td>391.32</td>\n",
       " <td>56,543</td>\n",
       " <td>42.7</td>\n",
       " <td>10.92</td>\n",
       " </tr>,\n",
       " <tr>\n",
       " <th scope=\"row\">페루</th>\n",
       " <td>516,296</td>\n",
       " <td>1569.29</td>\n",
       " <td>25,856</td>\n",
       " <td>78.6</td>\n",
       " <td>5.01</td>\n",
       " </tr>,\n",
       " <tr>\n",
       " <th scope=\"row\">콜롬비아</th>\n",
       " <td>433,805</td>\n",
       " <td>871.09</td>\n",
       " <td>14,145</td>\n",
       " <td>28.4</td>\n",
       " <td>3.26</td>\n",
       " </tr>,\n",
       " <tr>\n",
       " <th scope=\"row\">칠레</th>\n",
       " <td>383,902</td>\n",
       " <td>2049.66</td>\n",
       " <td>10,395</td>\n",
       " <td>55.5</td>\n",
       " <td>2.71</td>\n",
       " </tr>,\n",
       " <tr>\n",
       " <th scope=\"row\">스페인</th>\n",
       " <td>342,813</td>\n",
       " <td>738.82</td>\n",
       " <td>28,617</td>\n",
       " <td>61.7</td>\n",
       " <td>8.35</td>\n",
       " </tr>,\n",
       " <tr>\n",
       " <th scope=\"row\">이란</th>\n",
       " <td>341,070</td>\n",
       " <td>411.92</td>\n",
       " <td>19,492</td>\n",
       " <td>23.5</td>\n",
       " <td>5.71</td>\n",
       " </tr>,\n",
       " <tr>\n",
       " <th scope=\"row\">영국</th>\n",
       " <td>317,379</td>\n",
       " <td>473.7</td>\n",
       " <td>41,361</td>\n",
       " <td>61.7</td>\n",
       " <td>13.03</td>\n",
       " </tr>,\n",
       " <tr>\n",
       " <th scope=\"row\">사우디아라비아</th>\n",
       " <td>297,315</td>\n",
       " <td>871.89</td>\n",
       " <td>3,369</td>\n",
       " <td>9.9</td>\n",
       " <td>1.13</td>\n",
       " </tr>,\n",
       " <tr>\n",
       " <th scope=\"row\">파키스탄</th>\n",
       " <td>288,047</td>\n",
       " <td>140.79</td>\n",
       " <td>6,162</td>\n",
       " <td>3.0</td>\n",
       " <td>2.14</td>\n",
       " </tr>,\n",
       " <tr>\n",
       " <th scope=\"row\">아르헨티나</th>\n",
       " <td>276,072</td>\n",
       " <td>612.13</td>\n",
       " <td>5,428</td>\n",
       " <td>12.0</td>\n",
       " <td>1.97</td>\n",
       " </tr>,\n",
       " <tr>\n",
       " <th scope=\"row\">방글라데시</th>\n",
       " <td>271,881</td>\n",
       " <td>168.45</td>\n",
       " <td>3,591</td>\n",
       " <td>2.2</td>\n",
       " <td>1.32</td>\n",
       " </tr>,\n",
       " <tr>\n",
       " <th scope=\"row\">이탈리아</th>\n",
       " <td>253,438</td>\n",
       " <td>428.1</td>\n",
       " <td>35,392</td>\n",
       " <td>59.8</td>\n",
       " <td>13.96</td>\n",
       " </tr>,\n",
       " <tr>\n",
       " <th scope=\"row\">필리핀</th>\n",
       " <td>153,660</td>\n",
       " <td>142.15</td>\n",
       " <td>2,442</td>\n",
       " <td>2.3</td>\n",
       " <td>1.59</td>\n",
       " </tr>,\n",
       " <tr>\n",
       " <th scope=\"row\">인도네시아</th>\n",
       " <td>135,123</td>\n",
       " <td>50.14</td>\n",
       " <td>6,021</td>\n",
       " <td>2.2</td>\n",
       " <td>4.46</td>\n",
       " </tr>,\n",
       " <tr>\n",
       " <th scope=\"row\">카자흐스탄</th>\n",
       " <td>119,781</td>\n",
       " <td>643.98</td>\n",
       " <td>1,433</td>\n",
       " <td>7.7</td>\n",
       " <td>1.2</td>\n",
       " </tr>,\n",
       " <tr>\n",
       " <th scope=\"row\">중국</th>\n",
       " <td>84,827</td>\n",
       " <td>5.97</td>\n",
       " <td>4,634</td>\n",
       " <td>0.3</td>\n",
       " <td>5.46</td>\n",
       " </tr>,\n",
       " <tr>\n",
       " <th scope=\"row\">싱가포르</th>\n",
       " <td>55,661</td>\n",
       " <td>943.41</td>\n",
       " <td>27</td>\n",
       " <td>0.5</td>\n",
       " <td>0.05</td>\n",
       " </tr>,\n",
       " <tr>\n",
       " <th scope=\"row\">일본</th>\n",
       " <td>54,714</td>\n",
       " <td>43.12</td>\n",
       " <td>1,088</td>\n",
       " <td>0.9</td>\n",
       " <td>1.99</td>\n",
       " </tr>,\n",
       " <tr>\n",
       " <th scope=\"row\">키르키스스탄</th>\n",
       " <td>41,645</td>\n",
       " <td>671.69</td>\n",
       " <td>1,493</td>\n",
       " <td>24.1</td>\n",
       " <td>3.59</td>\n",
       " </tr>,\n",
       " <tr>\n",
       " <th scope=\"row\">우즈베키스탄</th>\n",
       " <td>34,251</td>\n",
       " <td>104.42</td>\n",
       " <td>223</td>\n",
       " <td>0.7</td>\n",
       " <td>0.65</td>\n",
       " </tr>,\n",
       " <tr>\n",
       " <th scope=\"row\">호주</th>\n",
       " <td>22,743</td>\n",
       " <td>90.61</td>\n",
       " <td>375</td>\n",
       " <td>1.5</td>\n",
       " <td>1.65</td>\n",
       " </tr>,\n",
       " <tr>\n",
       " <th scope=\"row\">말레이시아</th>\n",
       " <td>9,149</td>\n",
       " <td>28.15</td>\n",
       " <td>125</td>\n",
       " <td>0.4</td>\n",
       " <td>1.37</td>\n",
       " </tr>,\n",
       " <tr>\n",
       " <th scope=\"row\">태국</th>\n",
       " <td>3,376</td>\n",
       " <td>4.87</td>\n",
       " <td>58</td>\n",
       " <td>0.1</td>\n",
       " <td>1.72</td>\n",
       " </tr>,\n",
       " <tr>\n",
       " <th scope=\"row\">베트남</th>\n",
       " <td>951</td>\n",
       " <td>1.0</td>\n",
       " <td>23</td>\n",
       " <td>0.0</td>\n",
       " <td>2.42</td>\n",
       " </tr>,\n",
       " <tr>\n",
       " <th scope=\"row\">한국</th>\n",
       " <td>15,318</td>\n",
       " <td>29.6</td>\n",
       " <td>305</td>\n",
       " <td>0.6</td>\n",
       " <td>1.99</td>\n",
       " </tr>]"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "tr"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "bs4.element.ResultSet"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "type(tr)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "미국\n",
      "5,356,244\n",
      "1627.54\n",
      "169,423\n",
      "51.5\n",
      "3.16\n",
      "\n",
      "----------\n",
      "\n",
      "브라질\n",
      "3,317,096\n",
      "1561.72\n",
      "107,232\n",
      "50.5\n",
      "3.23\n",
      "\n",
      "----------\n",
      "\n",
      "인도\n",
      "2,526,192\n",
      "184.57\n",
      "49,036\n",
      "3.6\n",
      "1.94\n",
      "\n",
      "----------\n",
      "\n",
      "러시아\n",
      "917,884\n",
      "637.86\n",
      "15,617\n",
      "10.9\n",
      "1.7\n",
      "\n",
      "----------\n",
      "\n",
      "남아프리카공화국\n",
      "579,140\n",
      "996.8\n",
      "11,556\n",
      "19.9\n",
      "2\n",
      "\n",
      "----------\n",
      "\n",
      "멕시코\n",
      "517,714\n",
      "391.32\n",
      "56,543\n",
      "42.7\n",
      "10.92\n",
      "\n",
      "----------\n",
      "\n",
      "페루\n",
      "516,296\n",
      "1569.29\n",
      "25,856\n",
      "78.6\n",
      "5.01\n",
      "\n",
      "----------\n",
      "\n",
      "콜롬비아\n",
      "433,805\n",
      "871.09\n",
      "14,145\n",
      "28.4\n",
      "3.26\n",
      "\n",
      "----------\n",
      "\n",
      "칠레\n",
      "383,902\n",
      "2049.66\n",
      "10,395\n",
      "55.5\n",
      "2.71\n",
      "\n",
      "----------\n",
      "\n",
      "스페인\n",
      "342,813\n",
      "738.82\n",
      "28,617\n",
      "61.7\n",
      "8.35\n",
      "\n",
      "----------\n",
      "\n",
      "이란\n",
      "341,070\n",
      "411.92\n",
      "19,492\n",
      "23.5\n",
      "5.71\n",
      "\n",
      "----------\n",
      "\n",
      "영국\n",
      "317,379\n",
      "473.7\n",
      "41,361\n",
      "61.7\n",
      "13.03\n",
      "\n",
      "----------\n",
      "\n",
      "사우디아라비아\n",
      "297,315\n",
      "871.89\n",
      "3,369\n",
      "9.9\n",
      "1.13\n",
      "\n",
      "----------\n",
      "\n",
      "파키스탄\n",
      "288,047\n",
      "140.79\n",
      "6,162\n",
      "3.0\n",
      "2.14\n",
      "\n",
      "----------\n",
      "\n",
      "아르헨티나\n",
      "276,072\n",
      "612.13\n",
      "5,428\n",
      "12.0\n",
      "1.97\n",
      "\n",
      "----------\n",
      "\n",
      "방글라데시\n",
      "271,881\n",
      "168.45\n",
      "3,591\n",
      "2.2\n",
      "1.32\n",
      "\n",
      "----------\n",
      "\n",
      "이탈리아\n",
      "253,438\n",
      "428.1\n",
      "35,392\n",
      "59.8\n",
      "13.96\n",
      "\n",
      "----------\n",
      "\n",
      "필리핀\n",
      "153,660\n",
      "142.15\n",
      "2,442\n",
      "2.3\n",
      "1.59\n",
      "\n",
      "----------\n",
      "\n",
      "인도네시아\n",
      "135,123\n",
      "50.14\n",
      "6,021\n",
      "2.2\n",
      "4.46\n",
      "\n",
      "----------\n",
      "\n",
      "카자흐스탄\n",
      "119,781\n",
      "643.98\n",
      "1,433\n",
      "7.7\n",
      "1.2\n",
      "\n",
      "----------\n",
      "\n",
      "중국\n",
      "84,827\n",
      "5.97\n",
      "4,634\n",
      "0.3\n",
      "5.46\n",
      "\n",
      "----------\n",
      "\n",
      "싱가포르\n",
      "55,661\n",
      "943.41\n",
      "27\n",
      "0.5\n",
      "0.05\n",
      "\n",
      "----------\n",
      "\n",
      "일본\n",
      "54,714\n",
      "43.12\n",
      "1,088\n",
      "0.9\n",
      "1.99\n",
      "\n",
      "----------\n",
      "\n",
      "키르키스스탄\n",
      "41,645\n",
      "671.69\n",
      "1,493\n",
      "24.1\n",
      "3.59\n",
      "\n",
      "----------\n",
      "\n",
      "우즈베키스탄\n",
      "34,251\n",
      "104.42\n",
      "223\n",
      "0.7\n",
      "0.65\n",
      "\n",
      "----------\n",
      "\n",
      "호주\n",
      "22,743\n",
      "90.61\n",
      "375\n",
      "1.5\n",
      "1.65\n",
      "\n",
      "----------\n",
      "\n",
      "말레이시아\n",
      "9,149\n",
      "28.15\n",
      "125\n",
      "0.4\n",
      "1.37\n",
      "\n",
      "----------\n",
      "\n",
      "태국\n",
      "3,376\n",
      "4.87\n",
      "58\n",
      "0.1\n",
      "1.72\n",
      "\n",
      "----------\n",
      "\n",
      "베트남\n",
      "951\n",
      "1.0\n",
      "23\n",
      "0.0\n",
      "2.42\n",
      "\n",
      "----------\n",
      "\n",
      "한국\n",
      "15,318\n",
      "29.6\n",
      "305\n",
      "0.6\n",
      "1.99\n",
      "\n",
      "----------\n"
     ]
    }
   ],
   "source": [
    "for i,a in enumerate(tr) :\n",
    "    if i >= 2 :\n",
    "        print(a.text)\n",
    "        print('-'*10)\n",
    "\n",
    "        "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "z = a.find_all(\"td\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "list_country = []\n",
    "for i,a in enumerate(tr) :\n",
    "    if i >= 2 :\n",
    "        b = a.find_all(\"td\")\n",
    "        \n",
    "        for k in b :\n",
    "           \n",
    "            list_country.append(k.text)\n",
    "            \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "list_country1 = list_country[0::5]\n",
    "list_country2 = list_country[1::5]\n",
    "list_country3 = list_country[2::5]\n",
    "list_country4 = list_country[3::5]\n",
    "list_country5 = list_country[4::5]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "unexpected EOF while parsing (<ipython-input-11-4531d241d4ef>, line 9)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;36m  File \u001b[1;32m\"<ipython-input-11-4531d241d4ef>\"\u001b[1;36m, line \u001b[1;32m9\u001b[0m\n\u001b[1;33m    \u001b[0m\n\u001b[1;37m    ^\u001b[0m\n\u001b[1;31mSyntaxError\u001b[0m\u001b[1;31m:\u001b[0m unexpected EOF while parsing\n"
     ]
    }
   ],
   "source": [
    "for i,a in enumerate(tr) :\n",
    "    if i >= 2 :\n",
    "        b = a.find_all(\"td\")\n",
    "        for k in b :\n",
    "            list_country = []\n",
    "            list_country.append(k)\n",
    "            if len(list_country) == 5 :\n",
    "                \n",
    "            \n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    " # 내가한거 아니고 강사님이 알려주신 것\n",
    "    \n",
    "    \n",
    "    - 일단 그 tr 을 i, a 이런식으로 enumerate로 뽑아서 거기서 a에서 또 값들만 뽑아야 하니까 또\n",
    "    a를 \"td\"만 뽑아서 출력하면 또 리스트로 각각 나옴\n",
    "    근데 또 그 4개 값이 하나씩 나와야 하나의 열을 구성할 ㅅ누 있기 때문에 \n",
    "    또 td를 k로 뽑아내서 그 k가 4개씩 하낭늬 리스트로 나오면 또 그걸 하나씩 뽑아낸다 ... 오케이 !\n",
    "    \n",
    "    그래서 그 4개를 하나의 변수로 각기ㅏㄱ 저장하고 아까 국가리스트도 뽑아서 5개로 데이터프레임화 !!\n",
    "    \n",
    "    \n",
    "    \n",
    "    \n",
    "    \n",
    "    \n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "['3.16',\n",
       " '3.23',\n",
       " '1.94',\n",
       " '1.7',\n",
       " '2',\n",
       " '10.92',\n",
       " '5.01',\n",
       " '3.26',\n",
       " '2.71',\n",
       " '8.35',\n",
       " '5.71',\n",
       " '13.03',\n",
       " '1.13',\n",
       " '2.14',\n",
       " '1.97',\n",
       " '1.32',\n",
       " '13.96',\n",
       " '1.59',\n",
       " '4.46',\n",
       " '1.2',\n",
       " '5.46',\n",
       " '0.05',\n",
       " '1.99',\n",
       " '3.59',\n",
       " '0.65',\n",
       " '1.65',\n",
       " '1.37',\n",
       " '1.72',\n",
       " '2.42',\n",
       " '1.99']"
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "country_name\n",
    "list_country1\n",
    "list_country2 \n",
    "list_country3\n",
    "list_country4\n",
    "list_country5 "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{'미국': ['5,356,244', '1627.54']}"
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "dfd  = {}\n",
    "dfd[country_name[0]] = [list_country1[0], list_country2[0]]\n",
    "dfd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{'미국': ['5,356,244', '1627.54', '169,423', '51.5', '3.16'],\n",
       " '브라질': ['3,317,096', '1561.72', '107,232', '50.5', '3.23'],\n",
       " '인도': ['2,526,192', '184.57', '49,036', '3.6', '1.94'],\n",
       " '러시아': ['917,884', '637.86', '15,617', '10.9', '1.7'],\n",
       " '남아프리카공화국': ['579,140', '996.8', '11,556', '19.9', '2'],\n",
       " '멕시코': ['517,714', '391.32', '56,543', '42.7', '10.92'],\n",
       " '페루': ['516,296', '1569.29', '25,856', '78.6', '5.01'],\n",
       " '콜롬비아': ['433,805', '871.09', '14,145', '28.4', '3.26'],\n",
       " '칠레': ['383,902', '2049.66', '10,395', '55.5', '2.71'],\n",
       " '스페인': ['342,813', '738.82', '28,617', '61.7', '8.35'],\n",
       " '이란': ['341,070', '411.92', '19,492', '23.5', '5.71'],\n",
       " '영국': ['317,379', '473.7', '41,361', '61.7', '13.03'],\n",
       " '사우디아라비아': ['297,315', '871.89', '3,369', '9.9', '1.13'],\n",
       " '파키스탄': ['288,047', '140.79', '6,162', '3.0', '2.14'],\n",
       " '아르헨티나': ['276,072', '612.13', '5,428', '12.0', '1.97'],\n",
       " '방글라데시': ['271,881', '168.45', '3,591', '2.2', '1.32'],\n",
       " '이탈리아': ['253,438', '428.1', '35,392', '59.8', '13.96'],\n",
       " '필리핀': ['153,660', '142.15', '2,442', '2.3', '1.59'],\n",
       " '인도네시아': ['135,123', '50.14', '6,021', '2.2', '4.46'],\n",
       " '카자흐스탄': ['119,781', '643.98', '1,433', '7.7', '1.2'],\n",
       " '중국': ['84,827', '5.97', '4,634', '0.3', '5.46'],\n",
       " '싱가포르': ['55,661', '943.41', '27', '0.5', '0.05'],\n",
       " '일본': ['54,714', '43.12', '1,088', '0.9', '1.99'],\n",
       " '키르키스스탄': ['41,645', '671.69', '1,493', '24.1', '3.59'],\n",
       " '우즈베키스탄': ['34,251', '104.42', '223', '0.7', '0.65'],\n",
       " '호주': ['22,743', '90.61', '375', '1.5', '1.65'],\n",
       " '말레이시아': ['9,149', '28.15', '125', '0.4', '1.37'],\n",
       " '태국': ['3,376', '4.87', '58', '0.1', '1.72'],\n",
       " '베트남': ['951', '1.0', '23', '0.0', '2.42'],\n",
       " '한국': ['15,318', '29.6', '305', '0.6', '1.99']}"
      ]
     },
     "execution_count": 15,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "corona = {}\n",
    "for i in range(len(country_name)) :\n",
    "    corona[country_name[i]] = [list_country1[i],list_country2[i],list_country3[i]\n",
    "                               ,list_country4[i],list_country5[i]]\n",
    "\n",
    "corona"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [],
   "source": [
    "corona_file = pd.DataFrame(corona)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [],
   "source": [
    "corona_file1 = corona_file.copy() \n",
    "corona_file = corona_file1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>미국</th>\n",
       "      <th>브라질</th>\n",
       "      <th>인도</th>\n",
       "      <th>러시아</th>\n",
       "      <th>남아프리카공화국</th>\n",
       "      <th>멕시코</th>\n",
       "      <th>페루</th>\n",
       "      <th>콜롬비아</th>\n",
       "      <th>칠레</th>\n",
       "      <th>스페인</th>\n",
       "      <th>...</th>\n",
       "      <th>중국</th>\n",
       "      <th>싱가포르</th>\n",
       "      <th>일본</th>\n",
       "      <th>키르키스스탄</th>\n",
       "      <th>우즈베키스탄</th>\n",
       "      <th>호주</th>\n",
       "      <th>말레이시아</th>\n",
       "      <th>태국</th>\n",
       "      <th>베트남</th>\n",
       "      <th>한국</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>5,356,244</td>\n",
       "      <td>3,317,096</td>\n",
       "      <td>2,526,192</td>\n",
       "      <td>917,884</td>\n",
       "      <td>579,140</td>\n",
       "      <td>517,714</td>\n",
       "      <td>516,296</td>\n",
       "      <td>433,805</td>\n",
       "      <td>383,902</td>\n",
       "      <td>342,813</td>\n",
       "      <td>...</td>\n",
       "      <td>84,827</td>\n",
       "      <td>55,661</td>\n",
       "      <td>54,714</td>\n",
       "      <td>41,645</td>\n",
       "      <td>34,251</td>\n",
       "      <td>22,743</td>\n",
       "      <td>9,149</td>\n",
       "      <td>3,376</td>\n",
       "      <td>951</td>\n",
       "      <td>15,318</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1627.54</td>\n",
       "      <td>1561.72</td>\n",
       "      <td>184.57</td>\n",
       "      <td>637.86</td>\n",
       "      <td>996.8</td>\n",
       "      <td>391.32</td>\n",
       "      <td>1569.29</td>\n",
       "      <td>871.09</td>\n",
       "      <td>2049.66</td>\n",
       "      <td>738.82</td>\n",
       "      <td>...</td>\n",
       "      <td>5.97</td>\n",
       "      <td>943.41</td>\n",
       "      <td>43.12</td>\n",
       "      <td>671.69</td>\n",
       "      <td>104.42</td>\n",
       "      <td>90.61</td>\n",
       "      <td>28.15</td>\n",
       "      <td>4.87</td>\n",
       "      <td>1.0</td>\n",
       "      <td>29.6</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>169,423</td>\n",
       "      <td>107,232</td>\n",
       "      <td>49,036</td>\n",
       "      <td>15,617</td>\n",
       "      <td>11,556</td>\n",
       "      <td>56,543</td>\n",
       "      <td>25,856</td>\n",
       "      <td>14,145</td>\n",
       "      <td>10,395</td>\n",
       "      <td>28,617</td>\n",
       "      <td>...</td>\n",
       "      <td>4,634</td>\n",
       "      <td>27</td>\n",
       "      <td>1,088</td>\n",
       "      <td>1,493</td>\n",
       "      <td>223</td>\n",
       "      <td>375</td>\n",
       "      <td>125</td>\n",
       "      <td>58</td>\n",
       "      <td>23</td>\n",
       "      <td>305</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>51.5</td>\n",
       "      <td>50.5</td>\n",
       "      <td>3.6</td>\n",
       "      <td>10.9</td>\n",
       "      <td>19.9</td>\n",
       "      <td>42.7</td>\n",
       "      <td>78.6</td>\n",
       "      <td>28.4</td>\n",
       "      <td>55.5</td>\n",
       "      <td>61.7</td>\n",
       "      <td>...</td>\n",
       "      <td>0.3</td>\n",
       "      <td>0.5</td>\n",
       "      <td>0.9</td>\n",
       "      <td>24.1</td>\n",
       "      <td>0.7</td>\n",
       "      <td>1.5</td>\n",
       "      <td>0.4</td>\n",
       "      <td>0.1</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.6</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>3.16</td>\n",
       "      <td>3.23</td>\n",
       "      <td>1.94</td>\n",
       "      <td>1.7</td>\n",
       "      <td>2</td>\n",
       "      <td>10.92</td>\n",
       "      <td>5.01</td>\n",
       "      <td>3.26</td>\n",
       "      <td>2.71</td>\n",
       "      <td>8.35</td>\n",
       "      <td>...</td>\n",
       "      <td>5.46</td>\n",
       "      <td>0.05</td>\n",
       "      <td>1.99</td>\n",
       "      <td>3.59</td>\n",
       "      <td>0.65</td>\n",
       "      <td>1.65</td>\n",
       "      <td>1.37</td>\n",
       "      <td>1.72</td>\n",
       "      <td>2.42</td>\n",
       "      <td>1.99</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>5 rows × 30 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "          미국        브라질         인도      러시아 남아프리카공화국      멕시코       페루  \\\n",
       "0  5,356,244  3,317,096  2,526,192  917,884  579,140  517,714  516,296   \n",
       "1    1627.54    1561.72     184.57   637.86    996.8   391.32  1569.29   \n",
       "2    169,423    107,232     49,036   15,617   11,556   56,543   25,856   \n",
       "3       51.5       50.5        3.6     10.9     19.9     42.7     78.6   \n",
       "4       3.16       3.23       1.94      1.7        2    10.92     5.01   \n",
       "\n",
       "      콜롬비아       칠레      스페인  ...      중국    싱가포르      일본  키르키스스탄  우즈베키스탄  \\\n",
       "0  433,805  383,902  342,813  ...  84,827  55,661  54,714  41,645  34,251   \n",
       "1   871.09  2049.66   738.82  ...    5.97  943.41   43.12  671.69  104.42   \n",
       "2   14,145   10,395   28,617  ...   4,634      27   1,088   1,493     223   \n",
       "3     28.4     55.5     61.7  ...     0.3     0.5     0.9    24.1     0.7   \n",
       "4     3.26     2.71     8.35  ...    5.46    0.05    1.99    3.59    0.65   \n",
       "\n",
       "       호주  말레이시아     태국   베트남      한국  \n",
       "0  22,743  9,149  3,376   951  15,318  \n",
       "1   90.61  28.15   4.87   1.0    29.6  \n",
       "2     375    125     58    23     305  \n",
       "3     1.5    0.4    0.1   0.0     0.6  \n",
       "4    1.65   1.37   1.72  2.42    1.99  \n",
       "\n",
       "[5 rows x 30 columns]"
      ]
     },
     "execution_count": 18,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "corona_file"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "metadata": {},
   "outputs": [],
   "source": [
    "corona_file = corona_file.T"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "metadata": {},
   "outputs": [],
   "source": [
    "columns = ['감염인원','감염발생률','사망인원','사망발생률','사망률']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "metadata": {},
   "outputs": [],
   "source": [
    "corona_file.columns = columns"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>감염인원</th>\n",
       "      <th>감염발생률</th>\n",
       "      <th>사망인원</th>\n",
       "      <th>사망발생률</th>\n",
       "      <th>사망률</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>미국</th>\n",
       "      <td>5,356,244</td>\n",
       "      <td>1627.54</td>\n",
       "      <td>169,423</td>\n",
       "      <td>51.5</td>\n",
       "      <td>3.16</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>브라질</th>\n",
       "      <td>3,317,096</td>\n",
       "      <td>1561.72</td>\n",
       "      <td>107,232</td>\n",
       "      <td>50.5</td>\n",
       "      <td>3.23</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>인도</th>\n",
       "      <td>2,526,192</td>\n",
       "      <td>184.57</td>\n",
       "      <td>49,036</td>\n",
       "      <td>3.6</td>\n",
       "      <td>1.94</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>러시아</th>\n",
       "      <td>917,884</td>\n",
       "      <td>637.86</td>\n",
       "      <td>15,617</td>\n",
       "      <td>10.9</td>\n",
       "      <td>1.7</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>남아프리카공화국</th>\n",
       "      <td>579,140</td>\n",
       "      <td>996.8</td>\n",
       "      <td>11,556</td>\n",
       "      <td>19.9</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>멕시코</th>\n",
       "      <td>517,714</td>\n",
       "      <td>391.32</td>\n",
       "      <td>56,543</td>\n",
       "      <td>42.7</td>\n",
       "      <td>10.92</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>페루</th>\n",
       "      <td>516,296</td>\n",
       "      <td>1569.29</td>\n",
       "      <td>25,856</td>\n",
       "      <td>78.6</td>\n",
       "      <td>5.01</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>콜롬비아</th>\n",
       "      <td>433,805</td>\n",
       "      <td>871.09</td>\n",
       "      <td>14,145</td>\n",
       "      <td>28.4</td>\n",
       "      <td>3.26</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>칠레</th>\n",
       "      <td>383,902</td>\n",
       "      <td>2049.66</td>\n",
       "      <td>10,395</td>\n",
       "      <td>55.5</td>\n",
       "      <td>2.71</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>스페인</th>\n",
       "      <td>342,813</td>\n",
       "      <td>738.82</td>\n",
       "      <td>28,617</td>\n",
       "      <td>61.7</td>\n",
       "      <td>8.35</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>이란</th>\n",
       "      <td>341,070</td>\n",
       "      <td>411.92</td>\n",
       "      <td>19,492</td>\n",
       "      <td>23.5</td>\n",
       "      <td>5.71</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>영국</th>\n",
       "      <td>317,379</td>\n",
       "      <td>473.7</td>\n",
       "      <td>41,361</td>\n",
       "      <td>61.7</td>\n",
       "      <td>13.03</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>사우디아라비아</th>\n",
       "      <td>297,315</td>\n",
       "      <td>871.89</td>\n",
       "      <td>3,369</td>\n",
       "      <td>9.9</td>\n",
       "      <td>1.13</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>파키스탄</th>\n",
       "      <td>288,047</td>\n",
       "      <td>140.79</td>\n",
       "      <td>6,162</td>\n",
       "      <td>3.0</td>\n",
       "      <td>2.14</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>아르헨티나</th>\n",
       "      <td>276,072</td>\n",
       "      <td>612.13</td>\n",
       "      <td>5,428</td>\n",
       "      <td>12.0</td>\n",
       "      <td>1.97</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>방글라데시</th>\n",
       "      <td>271,881</td>\n",
       "      <td>168.45</td>\n",
       "      <td>3,591</td>\n",
       "      <td>2.2</td>\n",
       "      <td>1.32</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>이탈리아</th>\n",
       "      <td>253,438</td>\n",
       "      <td>428.1</td>\n",
       "      <td>35,392</td>\n",
       "      <td>59.8</td>\n",
       "      <td>13.96</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>필리핀</th>\n",
       "      <td>153,660</td>\n",
       "      <td>142.15</td>\n",
       "      <td>2,442</td>\n",
       "      <td>2.3</td>\n",
       "      <td>1.59</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>인도네시아</th>\n",
       "      <td>135,123</td>\n",
       "      <td>50.14</td>\n",
       "      <td>6,021</td>\n",
       "      <td>2.2</td>\n",
       "      <td>4.46</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>카자흐스탄</th>\n",
       "      <td>119,781</td>\n",
       "      <td>643.98</td>\n",
       "      <td>1,433</td>\n",
       "      <td>7.7</td>\n",
       "      <td>1.2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>중국</th>\n",
       "      <td>84,827</td>\n",
       "      <td>5.97</td>\n",
       "      <td>4,634</td>\n",
       "      <td>0.3</td>\n",
       "      <td>5.46</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>싱가포르</th>\n",
       "      <td>55,661</td>\n",
       "      <td>943.41</td>\n",
       "      <td>27</td>\n",
       "      <td>0.5</td>\n",
       "      <td>0.05</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>일본</th>\n",
       "      <td>54,714</td>\n",
       "      <td>43.12</td>\n",
       "      <td>1,088</td>\n",
       "      <td>0.9</td>\n",
       "      <td>1.99</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>키르키스스탄</th>\n",
       "      <td>41,645</td>\n",
       "      <td>671.69</td>\n",
       "      <td>1,493</td>\n",
       "      <td>24.1</td>\n",
       "      <td>3.59</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>우즈베키스탄</th>\n",
       "      <td>34,251</td>\n",
       "      <td>104.42</td>\n",
       "      <td>223</td>\n",
       "      <td>0.7</td>\n",
       "      <td>0.65</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>호주</th>\n",
       "      <td>22,743</td>\n",
       "      <td>90.61</td>\n",
       "      <td>375</td>\n",
       "      <td>1.5</td>\n",
       "      <td>1.65</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>말레이시아</th>\n",
       "      <td>9,149</td>\n",
       "      <td>28.15</td>\n",
       "      <td>125</td>\n",
       "      <td>0.4</td>\n",
       "      <td>1.37</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>태국</th>\n",
       "      <td>3,376</td>\n",
       "      <td>4.87</td>\n",
       "      <td>58</td>\n",
       "      <td>0.1</td>\n",
       "      <td>1.72</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>베트남</th>\n",
       "      <td>951</td>\n",
       "      <td>1.0</td>\n",
       "      <td>23</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2.42</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>한국</th>\n",
       "      <td>15,318</td>\n",
       "      <td>29.6</td>\n",
       "      <td>305</td>\n",
       "      <td>0.6</td>\n",
       "      <td>1.99</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "               감염인원    감염발생률     사망인원 사망발생률    사망률\n",
       "미국        5,356,244  1627.54  169,423  51.5   3.16\n",
       "브라질       3,317,096  1561.72  107,232  50.5   3.23\n",
       "인도        2,526,192   184.57   49,036   3.6   1.94\n",
       "러시아         917,884   637.86   15,617  10.9    1.7\n",
       "남아프리카공화국    579,140    996.8   11,556  19.9      2\n",
       "멕시코         517,714   391.32   56,543  42.7  10.92\n",
       "페루          516,296  1569.29   25,856  78.6   5.01\n",
       "콜롬비아        433,805   871.09   14,145  28.4   3.26\n",
       "칠레          383,902  2049.66   10,395  55.5   2.71\n",
       "스페인         342,813   738.82   28,617  61.7   8.35\n",
       "이란          341,070   411.92   19,492  23.5   5.71\n",
       "영국          317,379    473.7   41,361  61.7  13.03\n",
       "사우디아라비아     297,315   871.89    3,369   9.9   1.13\n",
       "파키스탄        288,047   140.79    6,162   3.0   2.14\n",
       "아르헨티나       276,072   612.13    5,428  12.0   1.97\n",
       "방글라데시       271,881   168.45    3,591   2.2   1.32\n",
       "이탈리아        253,438    428.1   35,392  59.8  13.96\n",
       "필리핀         153,660   142.15    2,442   2.3   1.59\n",
       "인도네시아       135,123    50.14    6,021   2.2   4.46\n",
       "카자흐스탄       119,781   643.98    1,433   7.7    1.2\n",
       "중국           84,827     5.97    4,634   0.3   5.46\n",
       "싱가포르         55,661   943.41       27   0.5   0.05\n",
       "일본           54,714    43.12    1,088   0.9   1.99\n",
       "키르키스스탄       41,645   671.69    1,493  24.1   3.59\n",
       "우즈베키스탄       34,251   104.42      223   0.7   0.65\n",
       "호주           22,743    90.61      375   1.5   1.65\n",
       "말레이시아         9,149    28.15      125   0.4   1.37\n",
       "태국            3,376     4.87       58   0.1   1.72\n",
       "베트남             951      1.0       23   0.0   2.42\n",
       "한국           15,318     29.6      305   0.6   1.99"
      ]
     },
     "execution_count": 32,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "corona_file \n",
    "#완성 !!"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 33,
   "metadata": {},
   "outputs": [],
   "source": [
    "import requests\n",
    "from bs4 import BeautifulSoup\n",
    "url = \"http://ncov.mohw.go.kr/bdBoardList_Real.do?brdId=1&brdGubun=14&ncvContSeq=&contSeq=&board_id=&gubun=\"\n",
    "html = requests.get(url).text\n",
    "soup = BeautifulSoup(html, \"html.parser\")\n",
    "all = soup.find(\"div\" , {\"class\" : \"data_table mgt16\"})\n",
    "\n",
    "th = all.find_all(\"th\",{'scope': 'col'})\n",
    "th_cont = all.find_all(\"th\", {\"scope\" : 'row'})\n",
    "td = all.find_all(\"td\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 34,
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "list_con = []\n",
    "dict_country = {}\n",
    "for i in td :\n",
    "    i = i.text\n",
    "    i = i.replace('\\t','')\n",
    "    i = i.replace('\\r','')\n",
    "    i = i.replace('\\n','')\n",
    "    list_con.append(i)\n",
    "    \n",
    "\n",
    "gukga = list_con[:370:2]\n",
    "samang = list_con[1::2]\n",
    "for a in range(len(gukga)) :\n",
    "    dict_country[gukga[a]] = [samang[a]]\n",
    "    \n",
    "    \n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 35,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[<th rowspan=\"29\" scope=\"row\">아시아</th>,\n",
       " <th rowspan=\"18\" scope=\"row\">중동</th>,\n",
       " <th rowspan=\"35\" scope=\"row\">아메리카</th>,\n",
       " <th rowspan=\"49\" scope=\"row\">유럽</th>,\n",
       " <th rowspan=\"4\" scope=\"row\">오세아니아</th>,\n",
       " <th rowspan=\"49\" scope=\"row\">아프리카</th>,\n",
       " <th rowspan=\"1\" scope=\"row\">기타</th>,\n",
       " <th colspan=\"2\" scope=\"row\">합계</th>]"
      ]
     },
     "execution_count": 35,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "th_cont"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 36,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "['중국',\n",
       " '홍콩',\n",
       " '대만',\n",
       " '마카오',\n",
       " '일본',\n",
       " '싱가포르',\n",
       " '태국',\n",
       " '말레이시아',\n",
       " '베트남',\n",
       " '인도',\n",
       " '필리핀',\n",
       " '캄보디아',\n",
       " '네팔',\n",
       " '스리랑카',\n",
       " '아프가니스탄',\n",
       " '파키스탄',\n",
       " '인도네시아',\n",
       " '부탄',\n",
       " '몰디브',\n",
       " '방글라데시',\n",
       " '브루나이',\n",
       " '몽골',\n",
       " '카자흐스탄',\n",
       " '우즈베키스탄',\n",
       " '키르기스스탄',\n",
       " '동티모르',\n",
       " '미얀마',\n",
       " '라오스',\n",
       " '타지키스탄',\n",
       " '이란',\n",
       " '바레인',\n",
       " '이집트',\n",
       " '이라크',\n",
       " '요르단',\n",
       " '쿠웨이트',\n",
       " '레바논',\n",
       " '리비아',\n",
       " '모로코',\n",
       " '오만',\n",
       " '카타르',\n",
       " '사우디아라비아',\n",
       " '시리아',\n",
       " '튀니지',\n",
       " '이스라엘',\n",
       " '아랍에미리트',\n",
       " '알제리',\n",
       " '예멘',\n",
       " '미국',\n",
       " '캐나다',\n",
       " '멕시코',\n",
       " '파나마',\n",
       " '온두라스',\n",
       " '과테말라',\n",
       " '코스타리카',\n",
       " '엘살바도르',\n",
       " '벨리즈',\n",
       " '니카라구아',\n",
       " '도미니카공화국',\n",
       " '쿠바',\n",
       " '자메이카',\n",
       " '트리니다드토바고',\n",
       " '아이티',\n",
       " '바하마',\n",
       " '바베이도스',\n",
       " '앤티가바부다',\n",
       " '그레나다',\n",
       " '세인트루시아',\n",
       " '세인트빈센트그레나딘',\n",
       " '도미니카연방',\n",
       " '세인트키츠네비스',\n",
       " '브라질',\n",
       " '페루',\n",
       " '에콰도르',\n",
       " '칠레',\n",
       " '콜롬비아',\n",
       " '아르헨티나',\n",
       " '볼리비아',\n",
       " '우루과이',\n",
       " '파라과이',\n",
       " '베네수엘라',\n",
       " '가이아나',\n",
       " '수리남',\n",
       " '이탈리아',\n",
       " '독일',\n",
       " '프랑스',\n",
       " '영국',\n",
       " '스페인',\n",
       " '오스트리아',\n",
       " '크로아티아',\n",
       " '핀란드',\n",
       " '스웨덴',\n",
       " '스위스',\n",
       " '벨기에',\n",
       " '덴마크',\n",
       " '에스토니아',\n",
       " '조지아',\n",
       " '그리스',\n",
       " '북마케도니아',\n",
       " '노르웨이',\n",
       " '루마니아',\n",
       " '네덜란드',\n",
       " '벨라루스',\n",
       " '리투아니아',\n",
       " '산마리노',\n",
       " '아제르바이잔',\n",
       " '아이슬란드',\n",
       " '모나코',\n",
       " '룩셈부르크',\n",
       " '아르메니아',\n",
       " '아일랜드',\n",
       " '체코',\n",
       " '포르투갈',\n",
       " '라트비아',\n",
       " '안도라',\n",
       " '폴란드',\n",
       " '우크라이나',\n",
       " '헝가리',\n",
       " '보스니아 헤르체고비나',\n",
       " '슬로베니아',\n",
       " '리히텐슈타인',\n",
       " '세르비아',\n",
       " '슬로바키아',\n",
       " '불가리아',\n",
       " '몰타',\n",
       " '몰도바',\n",
       " '알바니아',\n",
       " '사이프러스',\n",
       " '터키',\n",
       " '몬테네그로',\n",
       " '코소보',\n",
       " '러시아',\n",
       " '호주',\n",
       " '뉴질랜드',\n",
       " '피지',\n",
       " '파푸아뉴기니',\n",
       " '나이지리아',\n",
       " '세네갈',\n",
       " '카메룬',\n",
       " '남아프리카공화국',\n",
       " '토고',\n",
       " '부르키나파소',\n",
       " 'DR콩고',\n",
       " '코트디부아르',\n",
       " '수단',\n",
       " '에티오피아',\n",
       " '가봉',\n",
       " '가나',\n",
       " '기니',\n",
       " '케냐',\n",
       " '나미비아',\n",
       " '중앙아프리카공화국',\n",
       " '콩고',\n",
       " '적도기니',\n",
       " '에스와티니',\n",
       " '모리타니아',\n",
       " '르완다',\n",
       " '세이쉘',\n",
       " '베냉',\n",
       " '라이베리아',\n",
       " '탄자니아',\n",
       " '지부티',\n",
       " '감비아',\n",
       " '잠비아',\n",
       " '모리셔스',\n",
       " '차드',\n",
       " '니제르',\n",
       " '카보베르데',\n",
       " '짐바브웨',\n",
       " '소말리아',\n",
       " '마다가스카르',\n",
       " '앙골라',\n",
       " '에리트레아',\n",
       " '우간다',\n",
       " '모잠비크',\n",
       " '기니비사우',\n",
       " '말리',\n",
       " '보츠와나',\n",
       " '브룬디',\n",
       " '시에라리온',\n",
       " '말라위',\n",
       " '남수단',\n",
       " '상투메프린시페',\n",
       " '코모로',\n",
       " '레소토',\n",
       " '기타지역 영토']"
      ]
     },
     "execution_count": 36,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "gukga"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 37,
   "metadata": {},
   "outputs": [],
   "source": [
    "all_corona_file = pd.DataFrame(dict_country)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 38,
   "metadata": {},
   "outputs": [],
   "source": [
    "all_corona_file =all_corona_file.T"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 39,
   "metadata": {},
   "outputs": [],
   "source": [
    "all_corona_file.columns = ['환자발새 수 (사망)']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 131,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>환자발새 수 (사망)</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>중국</th>\n",
       "      <td>84,827명(사망 4,634)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>홍콩</th>\n",
       "      <td>4,406명(사망 69)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>대만</th>\n",
       "      <td>482명(사망 7)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>마카오</th>\n",
       "      <td>46명</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>일본</th>\n",
       "      <td>54,714명(사망 1,088)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>남수단</th>\n",
       "      <td>2,488명(사망 47)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>상투메프린시페</th>\n",
       "      <td>885명(사망 15)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>코모로</th>\n",
       "      <td>403명(사망 7)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>레소토</th>\n",
       "      <td>903명(사망 25)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>기타지역 영토</th>\n",
       "      <td>65,592명(사망 700)</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>185 rows × 1 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "               환자발새 수 (사망)\n",
       "중국       84,827명(사망 4,634)\n",
       "홍콩           4,406명(사망 69)\n",
       "대만              482명(사망 7)\n",
       "마카오                    46명\n",
       "일본       54,714명(사망 1,088)\n",
       "...                    ...\n",
       "남수단          2,488명(사망 47)\n",
       "상투메프린시페        885명(사망 15)\n",
       "코모로             403명(사망 7)\n",
       "레소토            903명(사망 25)\n",
       "기타지역 영토    65,592명(사망 700)\n",
       "\n",
       "[185 rows x 1 columns]"
      ]
     },
     "execution_count": 131,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "all_corona_file"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 132,
   "metadata": {},
   "outputs": [],
   "source": [
    "dict_all2 = {}\n",
    "asia = []\n",
    "middle = []\n",
    "america = []\n",
    "europe=[]\n",
    "osania = []\n",
    "africa= []\n",
    "etc = []\n",
    "for i in range(0,len(gukga)) :\n",
    "    if i >= 0 and i < 29  :\n",
    "        asia.append(gukga[i])\n",
    "        \n",
    "        dict_all2[gukga[i]] = 'asia'\n",
    "    \n",
    "    elif i>= 1+29-1 and i< 1+29+18-1 : \n",
    "        middle.append(gukga[i])\n",
    "        \n",
    "        dict_all2[gukga[i]] = 'middle'\n",
    "    \n",
    "    elif i >= 1+29+18-1 and i < 30+18+35-1 :\n",
    "        america.append(gukga[i])\n",
    "        \n",
    "        dict_all2[gukga[i]] = 'america'\n",
    "    \n",
    "    elif i >= 30+18+35-1 and i < 30+18+35+49-1  :\n",
    "        europe.append(gukga[i])\n",
    "        \n",
    "        dict_all2[gukga[i]] = 'europe'\n",
    "    \n",
    "    elif i >= 30+18+35+49-1 and i < 30+18+35+49+4-1  :\n",
    "        osania.append(gukga[i])\n",
    "        \n",
    "        dict_all2[gukga[i]] = 'osania'\n",
    "    \n",
    "    elif i >= 30+18+35+49+4-1 and i < 30+18+35+49+4+49-1  :\n",
    "        africa.append(gukga[i])\n",
    "        \n",
    "        dict_all2[gukga[i]] = 'africa'\n",
    "    \n",
    "    else :\n",
    "        etc.append(gukga[i])\n",
    "        \n",
    "        dict_all2[gukga[i]] = 'etc'\n",
    "        \n",
    "   \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 134,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{'중국': 'asia',\n",
       " '홍콩': 'asia',\n",
       " '대만': 'asia',\n",
       " '마카오': 'asia',\n",
       " '일본': 'asia',\n",
       " '싱가포르': 'asia',\n",
       " '태국': 'asia',\n",
       " '말레이시아': 'asia',\n",
       " '베트남': 'asia',\n",
       " '인도': 'asia',\n",
       " '필리핀': 'asia',\n",
       " '캄보디아': 'asia',\n",
       " '네팔': 'asia',\n",
       " '스리랑카': 'asia',\n",
       " '아프가니스탄': 'asia',\n",
       " '파키스탄': 'asia',\n",
       " '인도네시아': 'asia',\n",
       " '부탄': 'asia',\n",
       " '몰디브': 'asia',\n",
       " '방글라데시': 'asia',\n",
       " '브루나이': 'asia',\n",
       " '몽골': 'asia',\n",
       " '카자흐스탄': 'asia',\n",
       " '우즈베키스탄': 'asia',\n",
       " '키르기스스탄': 'asia',\n",
       " '동티모르': 'asia',\n",
       " '미얀마': 'asia',\n",
       " '라오스': 'asia',\n",
       " '타지키스탄': 'asia',\n",
       " '이란': 'middle',\n",
       " '바레인': 'middle',\n",
       " '이집트': 'middle',\n",
       " '이라크': 'middle',\n",
       " '요르단': 'middle',\n",
       " '쿠웨이트': 'middle',\n",
       " '레바논': 'middle',\n",
       " '리비아': 'middle',\n",
       " '모로코': 'middle',\n",
       " '오만': 'middle',\n",
       " '카타르': 'middle',\n",
       " '사우디아라비아': 'middle',\n",
       " '시리아': 'middle',\n",
       " '튀니지': 'middle',\n",
       " '이스라엘': 'middle',\n",
       " '아랍에미리트': 'middle',\n",
       " '알제리': 'middle',\n",
       " '예멘': 'middle',\n",
       " '미국': 'america',\n",
       " '캐나다': 'america',\n",
       " '멕시코': 'america',\n",
       " '파나마': 'america',\n",
       " '온두라스': 'america',\n",
       " '과테말라': 'america',\n",
       " '코스타리카': 'america',\n",
       " '엘살바도르': 'america',\n",
       " '벨리즈': 'america',\n",
       " '니카라구아': 'america',\n",
       " '도미니카공화국': 'america',\n",
       " '쿠바': 'america',\n",
       " '자메이카': 'america',\n",
       " '트리니다드토바고': 'america',\n",
       " '아이티': 'america',\n",
       " '바하마': 'america',\n",
       " '바베이도스': 'america',\n",
       " '앤티가바부다': 'america',\n",
       " '그레나다': 'america',\n",
       " '세인트루시아': 'america',\n",
       " '세인트빈센트그레나딘': 'america',\n",
       " '도미니카연방': 'america',\n",
       " '세인트키츠네비스': 'america',\n",
       " '브라질': 'america',\n",
       " '페루': 'america',\n",
       " '에콰도르': 'america',\n",
       " '칠레': 'america',\n",
       " '콜롬비아': 'america',\n",
       " '아르헨티나': 'america',\n",
       " '볼리비아': 'america',\n",
       " '우루과이': 'america',\n",
       " '파라과이': 'america',\n",
       " '베네수엘라': 'america',\n",
       " '가이아나': 'america',\n",
       " '수리남': 'america',\n",
       " '이탈리아': 'europe',\n",
       " '독일': 'europe',\n",
       " '프랑스': 'europe',\n",
       " '영국': 'europe',\n",
       " '스페인': 'europe',\n",
       " '오스트리아': 'europe',\n",
       " '크로아티아': 'europe',\n",
       " '핀란드': 'europe',\n",
       " '스웨덴': 'europe',\n",
       " '스위스': 'europe',\n",
       " '벨기에': 'europe',\n",
       " '덴마크': 'europe',\n",
       " '에스토니아': 'europe',\n",
       " '조지아': 'europe',\n",
       " '그리스': 'europe',\n",
       " '북마케도니아': 'europe',\n",
       " '노르웨이': 'europe',\n",
       " '루마니아': 'europe',\n",
       " '네덜란드': 'europe',\n",
       " '벨라루스': 'europe',\n",
       " '리투아니아': 'europe',\n",
       " '산마리노': 'europe',\n",
       " '아제르바이잔': 'europe',\n",
       " '아이슬란드': 'europe',\n",
       " '모나코': 'europe',\n",
       " '룩셈부르크': 'europe',\n",
       " '아르메니아': 'europe',\n",
       " '아일랜드': 'europe',\n",
       " '체코': 'europe',\n",
       " '포르투갈': 'europe',\n",
       " '라트비아': 'europe',\n",
       " '안도라': 'europe',\n",
       " '폴란드': 'europe',\n",
       " '우크라이나': 'europe',\n",
       " '헝가리': 'europe',\n",
       " '보스니아 헤르체고비나': 'europe',\n",
       " '슬로베니아': 'europe',\n",
       " '리히텐슈타인': 'europe',\n",
       " '세르비아': 'europe',\n",
       " '슬로바키아': 'europe',\n",
       " '불가리아': 'europe',\n",
       " '몰타': 'europe',\n",
       " '몰도바': 'europe',\n",
       " '알바니아': 'europe',\n",
       " '사이프러스': 'europe',\n",
       " '터키': 'europe',\n",
       " '몬테네그로': 'europe',\n",
       " '코소보': 'europe',\n",
       " '러시아': 'europe',\n",
       " '호주': 'osania',\n",
       " '뉴질랜드': 'osania',\n",
       " '피지': 'osania',\n",
       " '파푸아뉴기니': 'osania',\n",
       " '나이지리아': 'africa',\n",
       " '세네갈': 'africa',\n",
       " '카메룬': 'africa',\n",
       " '남아프리카공화국': 'africa',\n",
       " '토고': 'africa',\n",
       " '부르키나파소': 'africa',\n",
       " 'DR콩고': 'africa',\n",
       " '코트디부아르': 'africa',\n",
       " '수단': 'africa',\n",
       " '에티오피아': 'africa',\n",
       " '가봉': 'africa',\n",
       " '가나': 'africa',\n",
       " '기니': 'africa',\n",
       " '케냐': 'africa',\n",
       " '나미비아': 'africa',\n",
       " '중앙아프리카공화국': 'africa',\n",
       " '콩고': 'africa',\n",
       " '적도기니': 'africa',\n",
       " '에스와티니': 'africa',\n",
       " '모리타니아': 'africa',\n",
       " '르완다': 'africa',\n",
       " '세이쉘': 'africa',\n",
       " '베냉': 'africa',\n",
       " '라이베리아': 'africa',\n",
       " '탄자니아': 'africa',\n",
       " '지부티': 'africa',\n",
       " '감비아': 'africa',\n",
       " '잠비아': 'africa',\n",
       " '모리셔스': 'africa',\n",
       " '차드': 'africa',\n",
       " '니제르': 'africa',\n",
       " '카보베르데': 'africa',\n",
       " '짐바브웨': 'africa',\n",
       " '소말리아': 'africa',\n",
       " '마다가스카르': 'africa',\n",
       " '앙골라': 'africa',\n",
       " '에리트레아': 'africa',\n",
       " '우간다': 'africa',\n",
       " '모잠비크': 'africa',\n",
       " '기니비사우': 'africa',\n",
       " '말리': 'africa',\n",
       " '보츠와나': 'africa',\n",
       " '브룬디': 'africa',\n",
       " '시에라리온': 'africa',\n",
       " '말라위': 'africa',\n",
       " '남수단': 'africa',\n",
       " '상투메프린시페': 'africa',\n",
       " '코모로': 'africa',\n",
       " '레소토': 'africa',\n",
       " '기타지역 영토': 'etc'}"
      ]
     },
     "execution_count": 134,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "dict_all2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 135,
   "metadata": {},
   "outputs": [],
   "source": [
    "a = pd.DataFrame(dict_all2,index=[0])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 137,
   "metadata": {},
   "outputs": [],
   "source": [
    "a= a.T"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 138,
   "metadata": {},
   "outputs": [],
   "source": [
    "c = pd.concat([a, all_corona_file], axis=1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 144,
   "metadata": {},
   "outputs": [],
   "source": [
    "corona_all = c.reset_index([0])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 146,
   "metadata": {},
   "outputs": [],
   "source": [
    "corona_all.columns = ['국가','대륙','환자발생 수 (사망)']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 148,
   "metadata": {},
   "outputs": [],
   "source": [
    "corona_all = corona_all[['대륙','국가','환자발생 수 (사망)']]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 150,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>대륙</th>\n",
       "      <th>국가</th>\n",
       "      <th>환자발생 수 (사망)</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>asia</td>\n",
       "      <td>중국</td>\n",
       "      <td>84,827명(사망 4,634)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>asia</td>\n",
       "      <td>홍콩</td>\n",
       "      <td>4,406명(사망 69)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>asia</td>\n",
       "      <td>대만</td>\n",
       "      <td>482명(사망 7)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>asia</td>\n",
       "      <td>마카오</td>\n",
       "      <td>46명</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>asia</td>\n",
       "      <td>일본</td>\n",
       "      <td>54,714명(사망 1,088)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>180</th>\n",
       "      <td>africa</td>\n",
       "      <td>남수단</td>\n",
       "      <td>2,488명(사망 47)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>181</th>\n",
       "      <td>africa</td>\n",
       "      <td>상투메프린시페</td>\n",
       "      <td>885명(사망 15)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>182</th>\n",
       "      <td>africa</td>\n",
       "      <td>코모로</td>\n",
       "      <td>403명(사망 7)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>183</th>\n",
       "      <td>africa</td>\n",
       "      <td>레소토</td>\n",
       "      <td>903명(사망 25)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>184</th>\n",
       "      <td>etc</td>\n",
       "      <td>기타지역 영토</td>\n",
       "      <td>65,592명(사망 700)</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>185 rows × 3 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "         대륙       국가        환자발생 수 (사망)\n",
       "0      asia       중국  84,827명(사망 4,634)\n",
       "1      asia       홍콩      4,406명(사망 69)\n",
       "2      asia       대만         482명(사망 7)\n",
       "3      asia      마카오                46명\n",
       "4      asia       일본  54,714명(사망 1,088)\n",
       "..      ...      ...                ...\n",
       "180  africa      남수단      2,488명(사망 47)\n",
       "181  africa  상투메프린시페        885명(사망 15)\n",
       "182  africa      코모로         403명(사망 7)\n",
       "183  africa      레소토        903명(사망 25)\n",
       "184     etc  기타지역 영토    65,592명(사망 700)\n",
       "\n",
       "[185 rows x 3 columns]"
      ]
     },
     "execution_count": 150,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "corona_all   #대륙 합치면 완성"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
